version: '3.8'

services:
  finance_db:
    image: postgres:16-alpine
    container_name: finance-postgres
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    ports:
      - "5432:5432"
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge