server:
  servlet:
    context-path: /personal-finance-tracker

db:
  url: jdbc:postgresql://localhost:5432/finance_db?currentSchema=public
  username: finance_user
  password: finance_pass
  changelog:
    file: classpath:/db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui