spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db?currentSchema=public
    username: finance_user
    password: finance_pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

spring-doc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    root: INFO
    com.zaxxer.hikari: WARN
    org.apache.tomcat: WARN